######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 12 10:22:05 2014
#
# MODIFIED for shipping with EDTpdv package ; top level (pdv_qtlib/..)
# makefile calls qmake with this file as an argument the first time it
# it wants to make pdv_qtlib, or any time pdv_qtlib/makefile isn not present
#
######################################################################

TEMPLATE = lib
CONFIG += qt staticlib resources release
#CONFIG += qt staticlib resources debug
DESTDIR = ..
TARGET=pdv_qt
DEPENDPATH += .. ../pdv_qtlib ../pdvplus ../edtimage
INCLUDEPATH += .. ../pdv_qtlib ../pdvplus ../edtimage
MAKEFILE = makefile
QMAKE_CXXFLAGS += -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-variable -Wno-unused-value -Wno-ignored-qualifiers -Wno-unused-but-set-variable

# Input
HEADERS += AppSettings.h \
           CamSelectTree.h \
           CamSelectTreeItem.h \
           CamSettingsDlg.h \
           CamSerialDlg.h \
           DisplaySkip.h \
           HelpDlg.h \
           contrastwidget.h \
           DevInfoMsgBox.h \
           DevSelectTree.h \
           DevSelectTreeItem.h \
           DisplayContrast.h \
           EdtIntervalData.h \
           EdtQtContrastCanvas.h \
           EdtQtDeviceDlg.h \
           EdtQtGraphicsItem.h \
           EdtQtHistoCanvas.h \
           EdtQtHistogramItem.h \
           EdtQtImageItem.h \
           EdtQtImageScene.h \
           EdtQtImageView.h \
           EdtQtImageViewer.h \
           EdtQtImageWindow.h \
           EdtQtLiveDisplay.h \
           EdtQtPixelDlg.h \
           EdtQtPixelTable.h \
           EdtQtPlotCanvas.h \
           EdtQtPlotCurve.h \
           EdtQtPlotView.h \
           EdtQtProfileCanvas.h \
           EdtQtFileInfo.h \
#           EdtQtRegisterDlg.h \
#           EdtQwtPlot.h \
           histowidget.h \
           profilewidget.h \
           qtcamselect.h

FORMS += CamSettingsDlg.ui \
         CamSerialDlg.ui \
         DisplaySkip.ui \
         HelpDlg.ui \
         contrastwidget.ui \
         EdtQtDeviceDlg.ui \
         EdtQtImageWindow.ui \
         EdtQtPixelDlg.ui \
         edtqtplotcurve.ui \
         histowidget.ui \
         profilewidget.ui \
         qtcamselect.ui

SOURCES += AppSettings.cpp \
           CamSelectTree.cpp \
           CamSelectTreeItem.cpp \
           CamSettingsDlg.cpp \
           CamSerialDlg.cpp \
           DisplaySkip.cpp \
           HelpDlg.cpp \
           contrastwidget.cpp \
           DevInfoMsgBox.cpp \
           DevSelectTree.cpp \
           DevSelectTreeItem.cpp \
           DisplayContrast.cpp \
           EdtIntervalData.cpp \
           EdtQtContrastCanvas.cpp \
           EdtQtDeviceDlg.cpp \
           EdtQtGraphicsItem.cpp \
           EdtQtHistoCanvas.cpp \
           EdtQtHistogramItem.cpp \
           EdtQtImageItem.cpp \
           EdtQtImageScene.cpp \
           EdtQtImageView.cpp \
           EdtQtImageViewer.cpp \
           EdtQtImageWindow.cpp \
           EdtQtLiveDisplay.cpp \
           EdtQtPixelDlg.cpp \
           EdtQtPixelTable.cpp \
           EdtQtPlotCanvas.cpp \
           EdtQtPlotCurve.cpp \
           EdtQtPlotView.cpp \
           EdtQtProfileCanvas.cpp \
           EdtQtFileInfo.cpp \
#           EdtQtRegisterDlg.cpp \
#           EdtQwtPlot.cpp \
           histowidget.cpp \
           profilewidget.cpp \
           qtcamselect.cpp

RESOURCES += pdv_qtlib.qrc qtcamselect.qrc
